services:
  smtp4dev:
    image: rnwood/smtp4dev:prerelease # https://github.com/rnwood/smtp4dev/issues/1515
    restart: always
    ports:
      - '5000:80'
      - '2525:25'
    volumes:
      - smtp4dev-data:/smtp4dev
      - ./smtp4dev.json:/smtp4dev/appsettings.json
volumes:
  smtp4dev-data:
